# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dcc264b985decc309e13ab7bb4b5c4469ff2a1f7d3e36cff11680a84e23cbfc997886517f2d814f9a0f60a0c097a634e90b782c8ac6d1a5f628276172ccc5e9

test:
  secret_key_base: 46bfaf828b139ea46c5f4b56ca468361890d245b150119bb71a09484e1e28891888607ab9e586e66558d9922a1255e920e11ee5d94e0945b556ec560f75a0525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
